services:
  site:
    network_mode: "host"
    container_name: aurora-docsy
    command: bash -c "npm i . && npm run start"
    image: docker.io/library/node:latest@sha256:0d6c471a14b6df88a897ca03bcd4c222a9fc2626b96dba2352753e3a496a5ac6
    working_dir: /srv/docs
    volumes:
      - "./:/srv/docs:Z"
    ports:
      - "3000:3000"
