name: check-spelling

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.fedora_version }}
  cancel-in-progress: true

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Check for typos
        uses: crate-ci/typos@02fc4a1c87a21f493a7c4cc57897917672db8437 # version 1.0.4
        with:
          files: ./README.md ./docs
          config: ./typos.toml
