name: check-spelling

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.fedora_version }}
  cancel-in-progress: true

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check for typos
        uses: crate-ci/typos@08fa78ceeee2d67506d19841c595e2f97da3407c # version 1.0.4
        with:
          files: ./README.md ./docs
          config: ./typos.toml
